// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: finance.proto

package finance

import (
	common "github.com/educonnect/educonnect/internal/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Invoice status enum
type InvoiceStatus int32

const (
	InvoiceStatus_INVOICE_STATUS_UNSPECIFIED InvoiceStatus = 0
	InvoiceStatus_INVOICE_STATUS_DRAFT       InvoiceStatus = 1
	InvoiceStatus_INVOICE_STATUS_PENDING     InvoiceStatus = 2
	InvoiceStatus_INVOICE_STATUS_PAID        InvoiceStatus = 3
	InvoiceStatus_INVOICE_STATUS_CANCELLED   InvoiceStatus = 4
	InvoiceStatus_INVOICE_STATUS_OVERDUE     InvoiceStatus = 5
)

// Enum value maps for InvoiceStatus.
var (
	InvoiceStatus_name = map[int32]string{
		0: "INVOICE_STATUS_UNSPECIFIED",
		1: "INVOICE_STATUS_DRAFT",
		2: "INVOICE_STATUS_PENDING",
		3: "INVOICE_STATUS_PAID",
		4: "INVOICE_STATUS_CANCELLED",
		5: "INVOICE_STATUS_OVERDUE",
	}
	InvoiceStatus_value = map[string]int32{
		"INVOICE_STATUS_UNSPECIFIED": 0,
		"INVOICE_STATUS_DRAFT":       1,
		"INVOICE_STATUS_PENDING":     2,
		"INVOICE_STATUS_PAID":        3,
		"INVOICE_STATUS_CANCELLED":   4,
		"INVOICE_STATUS_OVERDUE":     5,
	}
)

func (x InvoiceStatus) Enum() *InvoiceStatus {
	p := new(InvoiceStatus)
	*p = x
	return p
}

func (x InvoiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_finance_proto_enumTypes[0].Descriptor()
}

func (InvoiceStatus) Type() protoreflect.EnumType {
	return &file_finance_proto_enumTypes[0]
}

func (x InvoiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceStatus.Descriptor instead.
func (InvoiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

// Payment method enum
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED   PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CASH          PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD   PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_E_WALLET      PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CASH",
		2: "PAYMENT_METHOD_BANK_TRANSFER",
		3: "PAYMENT_METHOD_CREDIT_CARD",
		4: "PAYMENT_METHOD_E_WALLET",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":   0,
		"PAYMENT_METHOD_CASH":          1,
		"PAYMENT_METHOD_BANK_TRANSFER": 2,
		"PAYMENT_METHOD_CREDIT_CARD":   3,
		"PAYMENT_METHOD_E_WALLET":      4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_finance_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_finance_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_COMPLETED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_COMPLETED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDED":    4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_finance_proto_enumTypes[2].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_finance_proto_enumTypes[2]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

// Fee type
type FeeType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultAmount *common.Money          `protobuf:"bytes,4,opt,name=default_amount,json=defaultAmount,proto3" json:"default_amount,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeType) Reset() {
	*x = FeeType{}
	mi := &file_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeType) ProtoMessage() {}

func (x *FeeType) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeType.ProtoReflect.Descriptor instead.
func (*FeeType) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{0}
}

func (x *FeeType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeeType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeeType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeeType) GetDefaultAmount() *common.Money {
	if x != nil {
		return x.DefaultAmount
	}
	return nil
}

func (x *FeeType) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *FeeType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FeeType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Invoice
type Invoice struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId       string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items           []*InvoiceItem         `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount     *common.Money          `protobuf:"bytes,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	PaidAmount      *common.Money          `protobuf:"bytes,6,opt,name=paid_amount,json=paidAmount,proto3" json:"paid_amount,omitempty"`
	RemainingAmount *common.Money          `protobuf:"bytes,7,opt,name=remaining_amount,json=remainingAmount,proto3" json:"remaining_amount,omitempty"`
	Status          InvoiceStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=finance.InvoiceStatus" json:"status,omitempty"`
	Description     string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	DueDate         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	IssuedDate      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=issued_date,json=issuedDate,proto3" json:"issued_date,omitempty"`
	PaidDate        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=paid_date,json=paidDate,proto3" json:"paid_date,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Student         *common.UserRef        `protobuf:"bytes,15,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{1}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Invoice) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invoice) GetItems() []*InvoiceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Invoice) GetTotalAmount() *common.Money {
	if x != nil {
		return x.TotalAmount
	}
	return nil
}

func (x *Invoice) GetPaidAmount() *common.Money {
	if x != nil {
		return x.PaidAmount
	}
	return nil
}

func (x *Invoice) GetRemainingAmount() *common.Money {
	if x != nil {
		return x.RemainingAmount
	}
	return nil
}

func (x *Invoice) GetStatus() InvoiceStatus {
	if x != nil {
		return x.Status
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *Invoice) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Invoice) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Invoice) GetIssuedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedDate
	}
	return nil
}

func (x *Invoice) GetPaidDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidDate
	}
	return nil
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Invoice) GetStudent() *common.UserRef {
	if x != nil {
		return x.Student
	}
	return nil
}

// Invoice item
type InvoiceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	FeeTypeId     string                 `protobuf:"bytes,3,opt,name=fee_type_id,json=feeTypeId,proto3" json:"fee_type_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceItem) Reset() {
	*x = InvoiceItem{}
	mi := &file_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceItem) ProtoMessage() {}

func (x *InvoiceItem) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceItem.ProtoReflect.Descriptor instead.
func (*InvoiceItem) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{2}
}

func (x *InvoiceItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoiceItem) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *InvoiceItem) GetFeeTypeId() string {
	if x != nil {
		return x.FeeTypeId
	}
	return ""
}

func (x *InvoiceItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InvoiceItem) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *InvoiceItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InvoiceItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Payment
type Payment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceId      string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	TransactionId  string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount         *common.Money          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Method         PaymentMethod          `protobuf:"varint,5,opt,name=method,proto3,enum=finance.PaymentMethod" json:"method,omitempty"`
	Status         PaymentStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=finance.PaymentStatus" json:"status,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	PaymentGateway string                 `protobuf:"bytes,8,opt,name=payment_gateway,json=paymentGateway,proto3" json:"payment_gateway,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Payment) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Payment) GetPaymentGateway() string {
	if x != nil {
		return x.PaymentGateway
	}
	return ""
}

func (x *Payment) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Payment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Get invoice by ID
type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{4}
}

func (x *GetInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get invoices by student
type GetInvoicesByStudentRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StudentId     string                    `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesByStudentRequest) Reset() {
	*x = GetInvoicesByStudentRequest{}
	mi := &file_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesByStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesByStudentRequest) ProtoMessage() {}

func (x *GetInvoicesByStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesByStudentRequest.ProtoReflect.Descriptor instead.
func (*GetInvoicesByStudentRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{5}
}

func (x *GetInvoicesByStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetInvoicesByStudentRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Get invoices by user
type GetInvoicesByUserRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesByUserRequest) Reset() {
	*x = GetInvoicesByUserRequest{}
	mi := &file_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesByUserRequest) ProtoMessage() {}

func (x *GetInvoicesByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesByUserRequest.ProtoReflect.Descriptor instead.
func (*GetInvoicesByUserRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvoicesByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInvoicesByUserRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Create invoice request
type CreateInvoiceRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StudentId     string                      `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	UserId        string                      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CreateInvoiceItemRequest `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Description   string                      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *timestamppb.Timestamp      `protobuf:"bytes,5,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceRequest) Reset() {
	*x = CreateInvoiceRequest{}
	mi := &file_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceRequest) ProtoMessage() {}

func (x *CreateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInvoiceRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateInvoiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvoiceRequest) GetItems() []*CreateInvoiceItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateInvoiceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateInvoiceRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

type CreateInvoiceItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeTypeId     string                 `protobuf:"bytes,1,opt,name=fee_type_id,json=feeTypeId,proto3" json:"fee_type_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceItemRequest) Reset() {
	*x = CreateInvoiceItemRequest{}
	mi := &file_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceItemRequest) ProtoMessage() {}

func (x *CreateInvoiceItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceItemRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceItemRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{8}
}

func (x *CreateInvoiceItemRequest) GetFeeTypeId() string {
	if x != nil {
		return x.FeeTypeId
	}
	return ""
}

func (x *CreateInvoiceItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateInvoiceItemRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateInvoiceItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Update invoice status request
type UpdateInvoiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        InvoiceStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=finance.InvoiceStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvoiceStatusRequest) Reset() {
	*x = UpdateInvoiceStatusRequest{}
	mi := &file_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvoiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvoiceStatusRequest) ProtoMessage() {}

func (x *UpdateInvoiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvoiceStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvoiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateInvoiceStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInvoiceStatusRequest) GetStatus() InvoiceStatus {
	if x != nil {
		return x.Status
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *UpdateInvoiceStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Create payment request
type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId      string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Amount         *common.Money          `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method         PaymentMethod          `protobuf:"varint,3,opt,name=method,proto3,enum=finance.PaymentMethod" json:"method,omitempty"`
	TransactionId  string                 `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentGateway string                 `protobuf:"bytes,5,opt,name=payment_gateway,json=paymentGateway,proto3" json:"payment_gateway,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePaymentRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreatePaymentRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreatePaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentGateway() string {
	if x != nil {
		return x.PaymentGateway
	}
	return ""
}

func (x *CreatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Get payments by invoice
type GetPaymentsByInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsByInvoiceRequest) Reset() {
	*x = GetPaymentsByInvoiceRequest{}
	mi := &file_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsByInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsByInvoiceRequest) ProtoMessage() {}

func (x *GetPaymentsByInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsByInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsByInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentsByInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

// Get fee types
type GetFeeTypesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ActiveOnly    bool                      `protobuf:"varint,1,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeTypesRequest) Reset() {
	*x = GetFeeTypesRequest{}
	mi := &file_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeTypesRequest) ProtoMessage() {}

func (x *GetFeeTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeTypesRequest.ProtoReflect.Descriptor instead.
func (*GetFeeTypesRequest) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{12}
}

func (x *GetFeeTypesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *GetFeeTypesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{13}
}

func (x *GetInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type GetInvoicesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Invoices      []*Invoice                 `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesResponse) Reset() {
	*x = GetInvoicesResponse{}
	mi := &file_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesResponse) ProtoMessage() {}

func (x *GetInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{14}
}

func (x *GetInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *GetInvoicesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{15}
}

func (x *CreateInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type UpdateInvoiceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvoiceStatusResponse) Reset() {
	*x = UpdateInvoiceStatusResponse{}
	mi := &file_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvoiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvoiceStatusResponse) ProtoMessage() {}

func (x *UpdateInvoiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvoiceStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateInvoiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateInvoiceStatusResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

func (x *UpdateInvoiceStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse) Reset() {
	*x = GetPaymentsResponse{}
	mi := &file_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse) ProtoMessage() {}

func (x *GetPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{17}
}

func (x *GetPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

type CreatePaymentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Payment        *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	UpdatedInvoice *Invoice               `protobuf:"bytes,2,opt,name=updated_invoice,json=updatedInvoice,proto3" json:"updated_invoice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreatePaymentResponse) GetUpdatedInvoice() *Invoice {
	if x != nil {
		return x.UpdatedInvoice
	}
	return nil
}

type GetFeeTypesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	FeeTypes      []*FeeType                 `protobuf:"bytes,1,rep,name=fee_types,json=feeTypes,proto3" json:"fee_types,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeTypesResponse) Reset() {
	*x = GetFeeTypesResponse{}
	mi := &file_finance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeTypesResponse) ProtoMessage() {}

func (x *GetFeeTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeTypesResponse.ProtoReflect.Descriptor instead.
func (*GetFeeTypesResponse) Descriptor() ([]byte, []int) {
	return file_finance_proto_rawDescGZIP(), []int{19}
}

func (x *GetFeeTypesResponse) GetFeeTypes() []*FeeType {
	if x != nil {
		return x.FeeTypes
	}
	return nil
}

func (x *GetFeeTypesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_finance_proto protoreflect.FileDescriptor

const file_finance_proto_rawDesc = "" +
	"\n" +
	"\rfinance.proto\x12\afinance\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\aFeeType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\x0edefault_amount\x18\x04 \x01(\v2\r.common.MoneyR\rdefaultAmount\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xb9\x05\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12*\n" +
	"\x05items\x18\x04 \x03(\v2\x14.finance.InvoiceItemR\x05items\x120\n" +
	"\ftotal_amount\x18\x05 \x01(\v2\r.common.MoneyR\vtotalAmount\x12.\n" +
	"\vpaid_amount\x18\x06 \x01(\v2\r.common.MoneyR\n" +
	"paidAmount\x128\n" +
	"\x10remaining_amount\x18\a \x01(\v2\r.common.MoneyR\x0fremainingAmount\x12.\n" +
	"\x06status\x18\b \x01(\x0e2\x16.finance.InvoiceStatusR\x06status\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x125\n" +
	"\bdue_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12;\n" +
	"\vissued_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"issuedDate\x127\n" +
	"\tpaid_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bpaidDate\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12)\n" +
	"\astudent\x18\x0f \x01(\v2\x0f.common.UserRefR\astudent\"\xfc\x01\n" +
	"\vInvoiceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12\x1e\n" +
	"\vfee_type_id\x18\x03 \x01(\tR\tfeeTypeId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\x06amount\x18\x05 \x01(\v2\r.common.MoneyR\x06amount\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdc\x03\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.common.MoneyR\x06amount\x12.\n" +
	"\x06method\x18\x05 \x01(\x0e2\x16.finance.PaymentMethodR\x06method\x12.\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.finance.PaymentStatusR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12'\n" +
	"\x0fpayment_gateway\x18\b \x01(\tR\x0epaymentGateway\x123\n" +
	"\apaid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"#\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"w\n" +
	"\x1bGetInvoicesByStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"n\n" +
	"\x18GetInvoicesByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\xe0\x01\n" +
	"\x14CreateInvoiceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.finance.CreateInvoiceItemRequestR\x05items\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x125\n" +
	"\bdue_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\"\x9f\x01\n" +
	"\x18CreateInvoiceItemRequest\x12\x1e\n" +
	"\vfee_type_id\x18\x01 \x01(\tR\tfeeTypeId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12%\n" +
	"\x06amount\x18\x03 \x01(\v2\r.common.MoneyR\x06amount\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"t\n" +
	"\x1aUpdateInvoiceStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.finance.InvoiceStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xfe\x01\n" +
	"\x14CreatePaymentRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12%\n" +
	"\x06amount\x18\x02 \x01(\v2\r.common.MoneyR\x06amount\x12.\n" +
	"\x06method\x18\x03 \x01(\x0e2\x16.finance.PaymentMethodR\x06method\x12%\n" +
	"\x0etransaction_id\x18\x04 \x01(\tR\rtransactionId\x12'\n" +
	"\x0fpayment_gateway\x18\x05 \x01(\tR\x0epaymentGateway\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\"<\n" +
	"\x1bGetPaymentsByInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\"p\n" +
	"\x12GetFeeTypesRequest\x12\x1f\n" +
	"\vactive_only\x18\x01 \x01(\bR\n" +
	"activeOnly\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"@\n" +
	"\x12GetInvoiceResponse\x12*\n" +
	"\ainvoice\x18\x01 \x01(\v2\x10.finance.InvoiceR\ainvoice\"\x7f\n" +
	"\x13GetInvoicesResponse\x12,\n" +
	"\binvoices\x18\x01 \x03(\v2\x10.finance.InvoiceR\binvoices\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"C\n" +
	"\x15CreateInvoiceResponse\x12*\n" +
	"\ainvoice\x18\x01 \x01(\v2\x10.finance.InvoiceR\ainvoice\"c\n" +
	"\x1bUpdateInvoiceStatusResponse\x12*\n" +
	"\ainvoice\x18\x01 \x01(\v2\x10.finance.InvoiceR\ainvoice\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"C\n" +
	"\x13GetPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.finance.PaymentR\bpayments\"~\n" +
	"\x15CreatePaymentResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x10.finance.PaymentR\apayment\x129\n" +
	"\x0fupdated_invoice\x18\x02 \x01(\v2\x10.finance.InvoiceR\x0eupdatedInvoice\"\x80\x01\n" +
	"\x13GetFeeTypesResponse\x12-\n" +
	"\tfee_types\x18\x01 \x03(\v2\x10.finance.FeeTypeR\bfeeTypes\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination*\xb8\x01\n" +
	"\rInvoiceStatus\x12\x1e\n" +
	"\x1aINVOICE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INVOICE_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16INVOICE_STATUS_PENDING\x10\x02\x12\x17\n" +
	"\x13INVOICE_STATUS_PAID\x10\x03\x12\x1c\n" +
	"\x18INVOICE_STATUS_CANCELLED\x10\x04\x12\x1a\n" +
	"\x16INVOICE_STATUS_OVERDUE\x10\x05*\xa7\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CASH\x10\x01\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_METHOD_E_WALLET\x10\x04*\xa1\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x042\x85\x04\n" +
	"\x0eInvoiceService\x12E\n" +
	"\n" +
	"GetInvoice\x12\x1a.finance.GetInvoiceRequest\x1a\x1b.finance.GetInvoiceResponse\x12Z\n" +
	"\x14GetInvoicesByStudent\x12$.finance.GetInvoicesByStudentRequest\x1a\x1c.finance.GetInvoicesResponse\x12T\n" +
	"\x11GetInvoicesByUser\x12!.finance.GetInvoicesByUserRequest\x1a\x1c.finance.GetInvoicesResponse\x12N\n" +
	"\rCreateInvoice\x12\x1d.finance.CreateInvoiceRequest\x1a\x1e.finance.CreateInvoiceResponse\x12`\n" +
	"\x13UpdateInvoiceStatus\x12#.finance.UpdateInvoiceStatusRequest\x1a$.finance.UpdateInvoiceStatusResponse\x12H\n" +
	"\vGetFeeTypes\x12\x1b.finance.GetFeeTypesRequest\x1a\x1c.finance.GetFeeTypesResponse2\xbc\x01\n" +
	"\x0ePaymentService\x12N\n" +
	"\rCreatePayment\x12\x1d.finance.CreatePaymentRequest\x1a\x1e.finance.CreatePaymentResponse\x12Z\n" +
	"\x14GetPaymentsByInvoice\x12$.finance.GetPaymentsByInvoiceRequest\x1a\x1c.finance.GetPaymentsResponse2>\n" +
	"\x12FinanceUserService\x12(\n" +
	"\aGetUser\x12\f.common.UUID\x1a\x0f.common.UserRefB=Z;github.com/educonnect/educonnect/internal/pkg/proto/financeb\x06proto3"

var (
	file_finance_proto_rawDescOnce sync.Once
	file_finance_proto_rawDescData []byte
)

func file_finance_proto_rawDescGZIP() []byte {
	file_finance_proto_rawDescOnce.Do(func() {
		file_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)))
	})
	return file_finance_proto_rawDescData
}

var file_finance_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_finance_proto_goTypes = []any{
	(InvoiceStatus)(0),                  // 0: finance.InvoiceStatus
	(PaymentMethod)(0),                  // 1: finance.PaymentMethod
	(PaymentStatus)(0),                  // 2: finance.PaymentStatus
	(*FeeType)(nil),                     // 3: finance.FeeType
	(*Invoice)(nil),                     // 4: finance.Invoice
	(*InvoiceItem)(nil),                 // 5: finance.InvoiceItem
	(*Payment)(nil),                     // 6: finance.Payment
	(*GetInvoiceRequest)(nil),           // 7: finance.GetInvoiceRequest
	(*GetInvoicesByStudentRequest)(nil), // 8: finance.GetInvoicesByStudentRequest
	(*GetInvoicesByUserRequest)(nil),    // 9: finance.GetInvoicesByUserRequest
	(*CreateInvoiceRequest)(nil),        // 10: finance.CreateInvoiceRequest
	(*CreateInvoiceItemRequest)(nil),    // 11: finance.CreateInvoiceItemRequest
	(*UpdateInvoiceStatusRequest)(nil),  // 12: finance.UpdateInvoiceStatusRequest
	(*CreatePaymentRequest)(nil),        // 13: finance.CreatePaymentRequest
	(*GetPaymentsByInvoiceRequest)(nil), // 14: finance.GetPaymentsByInvoiceRequest
	(*GetFeeTypesRequest)(nil),          // 15: finance.GetFeeTypesRequest
	(*GetInvoiceResponse)(nil),          // 16: finance.GetInvoiceResponse
	(*GetInvoicesResponse)(nil),         // 17: finance.GetInvoicesResponse
	(*CreateInvoiceResponse)(nil),       // 18: finance.CreateInvoiceResponse
	(*UpdateInvoiceStatusResponse)(nil), // 19: finance.UpdateInvoiceStatusResponse
	(*GetPaymentsResponse)(nil),         // 20: finance.GetPaymentsResponse
	(*CreatePaymentResponse)(nil),       // 21: finance.CreatePaymentResponse
	(*GetFeeTypesResponse)(nil),         // 22: finance.GetFeeTypesResponse
	(*common.Money)(nil),                // 23: common.Money
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
	(*common.UserRef)(nil),              // 25: common.UserRef
	(*common.PaginationRequest)(nil),    // 26: common.PaginationRequest
	(*common.PaginationResponse)(nil),   // 27: common.PaginationResponse
	(*common.UUID)(nil),                 // 28: common.UUID
}
var file_finance_proto_depIdxs = []int32{
	23, // 0: finance.FeeType.default_amount:type_name -> common.Money
	24, // 1: finance.FeeType.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: finance.FeeType.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: finance.Invoice.items:type_name -> finance.InvoiceItem
	23, // 4: finance.Invoice.total_amount:type_name -> common.Money
	23, // 5: finance.Invoice.paid_amount:type_name -> common.Money
	23, // 6: finance.Invoice.remaining_amount:type_name -> common.Money
	0,  // 7: finance.Invoice.status:type_name -> finance.InvoiceStatus
	24, // 8: finance.Invoice.due_date:type_name -> google.protobuf.Timestamp
	24, // 9: finance.Invoice.issued_date:type_name -> google.protobuf.Timestamp
	24, // 10: finance.Invoice.paid_date:type_name -> google.protobuf.Timestamp
	24, // 11: finance.Invoice.created_at:type_name -> google.protobuf.Timestamp
	24, // 12: finance.Invoice.updated_at:type_name -> google.protobuf.Timestamp
	25, // 13: finance.Invoice.student:type_name -> common.UserRef
	23, // 14: finance.InvoiceItem.amount:type_name -> common.Money
	24, // 15: finance.InvoiceItem.created_at:type_name -> google.protobuf.Timestamp
	23, // 16: finance.Payment.amount:type_name -> common.Money
	1,  // 17: finance.Payment.method:type_name -> finance.PaymentMethod
	2,  // 18: finance.Payment.status:type_name -> finance.PaymentStatus
	24, // 19: finance.Payment.paid_at:type_name -> google.protobuf.Timestamp
	24, // 20: finance.Payment.created_at:type_name -> google.protobuf.Timestamp
	24, // 21: finance.Payment.updated_at:type_name -> google.protobuf.Timestamp
	26, // 22: finance.GetInvoicesByStudentRequest.pagination:type_name -> common.PaginationRequest
	26, // 23: finance.GetInvoicesByUserRequest.pagination:type_name -> common.PaginationRequest
	11, // 24: finance.CreateInvoiceRequest.items:type_name -> finance.CreateInvoiceItemRequest
	24, // 25: finance.CreateInvoiceRequest.due_date:type_name -> google.protobuf.Timestamp
	23, // 26: finance.CreateInvoiceItemRequest.amount:type_name -> common.Money
	0,  // 27: finance.UpdateInvoiceStatusRequest.status:type_name -> finance.InvoiceStatus
	23, // 28: finance.CreatePaymentRequest.amount:type_name -> common.Money
	1,  // 29: finance.CreatePaymentRequest.method:type_name -> finance.PaymentMethod
	26, // 30: finance.GetFeeTypesRequest.pagination:type_name -> common.PaginationRequest
	4,  // 31: finance.GetInvoiceResponse.invoice:type_name -> finance.Invoice
	4,  // 32: finance.GetInvoicesResponse.invoices:type_name -> finance.Invoice
	27, // 33: finance.GetInvoicesResponse.pagination:type_name -> common.PaginationResponse
	4,  // 34: finance.CreateInvoiceResponse.invoice:type_name -> finance.Invoice
	4,  // 35: finance.UpdateInvoiceStatusResponse.invoice:type_name -> finance.Invoice
	6,  // 36: finance.GetPaymentsResponse.payments:type_name -> finance.Payment
	6,  // 37: finance.CreatePaymentResponse.payment:type_name -> finance.Payment
	4,  // 38: finance.CreatePaymentResponse.updated_invoice:type_name -> finance.Invoice
	3,  // 39: finance.GetFeeTypesResponse.fee_types:type_name -> finance.FeeType
	27, // 40: finance.GetFeeTypesResponse.pagination:type_name -> common.PaginationResponse
	7,  // 41: finance.InvoiceService.GetInvoice:input_type -> finance.GetInvoiceRequest
	8,  // 42: finance.InvoiceService.GetInvoicesByStudent:input_type -> finance.GetInvoicesByStudentRequest
	9,  // 43: finance.InvoiceService.GetInvoicesByUser:input_type -> finance.GetInvoicesByUserRequest
	10, // 44: finance.InvoiceService.CreateInvoice:input_type -> finance.CreateInvoiceRequest
	12, // 45: finance.InvoiceService.UpdateInvoiceStatus:input_type -> finance.UpdateInvoiceStatusRequest
	15, // 46: finance.InvoiceService.GetFeeTypes:input_type -> finance.GetFeeTypesRequest
	13, // 47: finance.PaymentService.CreatePayment:input_type -> finance.CreatePaymentRequest
	14, // 48: finance.PaymentService.GetPaymentsByInvoice:input_type -> finance.GetPaymentsByInvoiceRequest
	28, // 49: finance.FinanceUserService.GetUser:input_type -> common.UUID
	16, // 50: finance.InvoiceService.GetInvoice:output_type -> finance.GetInvoiceResponse
	17, // 51: finance.InvoiceService.GetInvoicesByStudent:output_type -> finance.GetInvoicesResponse
	17, // 52: finance.InvoiceService.GetInvoicesByUser:output_type -> finance.GetInvoicesResponse
	18, // 53: finance.InvoiceService.CreateInvoice:output_type -> finance.CreateInvoiceResponse
	19, // 54: finance.InvoiceService.UpdateInvoiceStatus:output_type -> finance.UpdateInvoiceStatusResponse
	22, // 55: finance.InvoiceService.GetFeeTypes:output_type -> finance.GetFeeTypesResponse
	21, // 56: finance.PaymentService.CreatePayment:output_type -> finance.CreatePaymentResponse
	20, // 57: finance.PaymentService.GetPaymentsByInvoice:output_type -> finance.GetPaymentsResponse
	25, // 58: finance.FinanceUserService.GetUser:output_type -> common.UserRef
	50, // [50:59] is the sub-list for method output_type
	41, // [41:50] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_finance_proto_init() }
func file_finance_proto_init() {
	if File_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_proto_rawDesc), len(file_finance_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_finance_proto_goTypes,
		DependencyIndexes: file_finance_proto_depIdxs,
		EnumInfos:         file_finance_proto_enumTypes,
		MessageInfos:      file_finance_proto_msgTypes,
	}.Build()
	File_finance_proto = out.File
	file_finance_proto_goTypes = nil
	file_finance_proto_depIdxs = nil
}
