// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: notify.proto

package notify

import (
	common "github.com/educonnect/educonnect/internal/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Notification type enum
type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_EMAIL       NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_SMS         NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_PUSH        NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_IN_APP      NotificationType = 4
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_EMAIL",
		2: "NOTIFICATION_TYPE_SMS",
		3: "NOTIFICATION_TYPE_PUSH",
		4: "NOTIFICATION_TYPE_IN_APP",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"NOTIFICATION_TYPE_EMAIL":       1,
		"NOTIFICATION_TYPE_SMS":         2,
		"NOTIFICATION_TYPE_PUSH":        3,
		"NOTIFICATION_TYPE_IN_APP":      4,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

// Notification priority enum
type NotificationPriority int32

const (
	NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED NotificationPriority = 0
	NotificationPriority_NOTIFICATION_PRIORITY_LOW         NotificationPriority = 1
	NotificationPriority_NOTIFICATION_PRIORITY_NORMAL      NotificationPriority = 2
	NotificationPriority_NOTIFICATION_PRIORITY_HIGH        NotificationPriority = 3
	NotificationPriority_NOTIFICATION_PRIORITY_URGENT      NotificationPriority = 4
)

// Enum value maps for NotificationPriority.
var (
	NotificationPriority_name = map[int32]string{
		0: "NOTIFICATION_PRIORITY_UNSPECIFIED",
		1: "NOTIFICATION_PRIORITY_LOW",
		2: "NOTIFICATION_PRIORITY_NORMAL",
		3: "NOTIFICATION_PRIORITY_HIGH",
		4: "NOTIFICATION_PRIORITY_URGENT",
	}
	NotificationPriority_value = map[string]int32{
		"NOTIFICATION_PRIORITY_UNSPECIFIED": 0,
		"NOTIFICATION_PRIORITY_LOW":         1,
		"NOTIFICATION_PRIORITY_NORMAL":      2,
		"NOTIFICATION_PRIORITY_HIGH":        3,
		"NOTIFICATION_PRIORITY_URGENT":      4,
	}
)

func (x NotificationPriority) Enum() *NotificationPriority {
	p := new(NotificationPriority)
	*p = x
	return p
}

func (x NotificationPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[1].Descriptor()
}

func (NotificationPriority) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[1]
}

func (x NotificationPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationPriority.Descriptor instead.
func (NotificationPriority) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

// Notification status enum
type NotificationStatus int32

const (
	NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_NOTIFICATION_STATUS_PENDING     NotificationStatus = 1
	NotificationStatus_NOTIFICATION_STATUS_SENT        NotificationStatus = 2
	NotificationStatus_NOTIFICATION_STATUS_DELIVERED   NotificationStatus = 3
	NotificationStatus_NOTIFICATION_STATUS_FAILED      NotificationStatus = 4
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "NOTIFICATION_STATUS_UNSPECIFIED",
		1: "NOTIFICATION_STATUS_PENDING",
		2: "NOTIFICATION_STATUS_SENT",
		3: "NOTIFICATION_STATUS_DELIVERED",
		4: "NOTIFICATION_STATUS_FAILED",
	}
	NotificationStatus_value = map[string]int32{
		"NOTIFICATION_STATUS_UNSPECIFIED": 0,
		"NOTIFICATION_STATUS_PENDING":     1,
		"NOTIFICATION_STATUS_SENT":        2,
		"NOTIFICATION_STATUS_DELIVERED":   3,
		"NOTIFICATION_STATUS_FAILED":      4,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_notify_proto_enumTypes[2].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_notify_proto_enumTypes[2]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{2}
}

// Notification template
type NotificationTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Type          NotificationType       `protobuf:"varint,5,opt,name=type,proto3,enum=notify.NotificationType" json:"type,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value pairs for template substitution
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTemplate) Reset() {
	*x = NotificationTemplate{}
	mi := &file_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTemplate) ProtoMessage() {}

func (x *NotificationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTemplate.ProtoReflect.Descriptor instead.
func (*NotificationTemplate) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotificationTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationTemplate) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationTemplate) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationTemplate) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *NotificationTemplate) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *NotificationTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Notification
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Type          NotificationType       `protobuf:"varint,7,opt,name=type,proto3,enum=notify.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,8,opt,name=priority,proto3,enum=notify.NotificationPriority" json:"priority,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,9,opt,name=status,proto3,enum=notify.NotificationStatus" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional data
	TemplateId    string                 `protobuf:"bytes,11,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	RetryCount    int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Notification) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *Notification) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *Notification) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Notification) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Notification) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Notification) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Notification) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Notification) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Notification) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Invoice payment event (for integration with Finance service)
type InvoicePaymentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        *common.Money          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,5,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoicePaymentEvent) Reset() {
	*x = InvoicePaymentEvent{}
	mi := &file_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoicePaymentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoicePaymentEvent) ProtoMessage() {}

func (x *InvoicePaymentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoicePaymentEvent.ProtoReflect.Descriptor instead.
func (*InvoicePaymentEvent) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{2}
}

func (x *InvoicePaymentEvent) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *InvoicePaymentEvent) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *InvoicePaymentEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InvoicePaymentEvent) GetAmount() *common.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *InvoicePaymentEvent) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *InvoicePaymentEvent) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

// Send notification request
type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Type          NotificationType       `protobuf:"varint,6,opt,name=type,proto3,enum=notify.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,7,opt,name=priority,proto3,enum=notify.NotificationPriority" json:"priority,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{3}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendNotificationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendNotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *SendNotificationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Send notification using template
type SendTemplateNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Variables     map[string]string      `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Template variables
	Priority      NotificationPriority   `protobuf:"varint,6,opt,name=priority,proto3,enum=notify.NotificationPriority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTemplateNotificationRequest) Reset() {
	*x = SendTemplateNotificationRequest{}
	mi := &file_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTemplateNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTemplateNotificationRequest) ProtoMessage() {}

func (x *SendTemplateNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTemplateNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendTemplateNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{4}
}

func (x *SendTemplateNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendTemplateNotificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendTemplateNotificationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendTemplateNotificationRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendTemplateNotificationRequest) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *SendTemplateNotificationRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

// Send bulk notifications
type SendBulkNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Type          NotificationType       `protobuf:"varint,4,opt,name=type,proto3,enum=notify.NotificationType" json:"type,omitempty"`
	Priority      NotificationPriority   `protobuf:"varint,5,opt,name=priority,proto3,enum=notify.NotificationPriority" json:"priority,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkNotificationsRequest) Reset() {
	*x = SendBulkNotificationsRequest{}
	mi := &file_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkNotificationsRequest) ProtoMessage() {}

func (x *SendBulkNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkNotificationsRequest.ProtoReflect.Descriptor instead.
func (*SendBulkNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{5}
}

func (x *SendBulkNotificationsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendBulkNotificationsRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendBulkNotificationsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendBulkNotificationsRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *SendBulkNotificationsRequest) GetPriority() NotificationPriority {
	if x != nil {
		return x.Priority
	}
	return NotificationPriority_NOTIFICATION_PRIORITY_UNSPECIFIED
}

func (x *SendBulkNotificationsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Get notification by ID
type GetNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Get notifications by user
type GetNotificationsByUserRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        string                    `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        NotificationStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=notify.NotificationStatus" json:"status,omitempty"`
	Type          NotificationType          `protobuf:"varint,4,opt,name=type,proto3,enum=notify.NotificationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsByUserRequest) Reset() {
	*x = GetNotificationsByUserRequest{}
	mi := &file_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsByUserRequest) ProtoMessage() {}

func (x *GetNotificationsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsByUserRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{7}
}

func (x *GetNotificationsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNotificationsByUserRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetNotificationsByUserRequest) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_NOTIFICATION_STATUS_UNSPECIFIED
}

func (x *GetNotificationsByUserRequest) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

// Mark notification as read
type MarkAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{8}
}

func (x *MarkAsReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Mark all notifications as read for a user
type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{9}
}

func (x *MarkAllAsReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Process invoice payment event
type ProcessInvoicePaymentEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *InvoicePaymentEvent   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInvoicePaymentEventRequest) Reset() {
	*x = ProcessInvoicePaymentEventRequest{}
	mi := &file_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInvoicePaymentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInvoicePaymentEventRequest) ProtoMessage() {}

func (x *ProcessInvoicePaymentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInvoicePaymentEventRequest.ProtoReflect.Descriptor instead.
func (*ProcessInvoicePaymentEventRequest) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessInvoicePaymentEventRequest) GetEvent() *InvoicePaymentEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{11}
}

func (x *SendNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendBulkNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSent     int32                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,2,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	FailedUserIds []string               `protobuf:"bytes,3,rep,name=failed_user_ids,json=failedUserIds,proto3" json:"failed_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkNotificationsResponse) Reset() {
	*x = SendBulkNotificationsResponse{}
	mi := &file_notify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkNotificationsResponse) ProtoMessage() {}

func (x *SendBulkNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkNotificationsResponse.ProtoReflect.Descriptor instead.
func (*SendBulkNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{12}
}

func (x *SendBulkNotificationsResponse) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *SendBulkNotificationsResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *SendBulkNotificationsResponse) GetFailedUserIds() []string {
	if x != nil {
		return x.FailedUserIds
	}
	return nil
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_notify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{13}
}

func (x *GetNotificationResponse) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type GetNotificationsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Notifications []*Notification            `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_notify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{14}
}

func (x *GetNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_notify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{15}
}

func (x *MarkAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkAsReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProcessInvoicePaymentEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Notifications []*Notification        `protobuf:"bytes,3,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInvoicePaymentEventResponse) Reset() {
	*x = ProcessInvoicePaymentEventResponse{}
	mi := &file_notify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInvoicePaymentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInvoicePaymentEventResponse) ProtoMessage() {}

func (x *ProcessInvoicePaymentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInvoicePaymentEventResponse.ProtoReflect.Descriptor instead.
func (*ProcessInvoicePaymentEventResponse) Descriptor() ([]byte, []int) {
	return file_notify_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessInvoicePaymentEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcessInvoicePaymentEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessInvoicePaymentEventResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

var File_notify_proto protoreflect.FileDescriptor

const file_notify_proto_rawDesc = "" +
	"\n" +
	"\fnotify.proto\x12\x06notify\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x03\n" +
	"\x14NotificationTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12,\n" +
	"\x04type\x18\x05 \x01(\x0e2\x18.notify.NotificationTypeR\x04type\x12I\n" +
	"\tvariables\x18\x06 \x03(\v2+.notify.NotificationTemplate.VariablesEntryR\tvariables\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x06\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12,\n" +
	"\x04type\x18\a \x01(\x0e2\x18.notify.NotificationTypeR\x04type\x128\n" +
	"\bpriority\x18\b \x01(\x0e2\x1c.notify.NotificationPriorityR\bpriority\x122\n" +
	"\x06status\x18\t \x01(\x0e2\x1a.notify.NotificationStatusR\x06status\x12>\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\".notify.Notification.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vtemplate_id\x18\v \x01(\tR\n" +
	"templateId\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12=\n" +
	"\fscheduled_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x123\n" +
	"\asent_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12=\n" +
	"\fdelivered_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x13InvoicePaymentEvent\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12%\n" +
	"\x06amount\x18\x04 \x01(\v2\r.common.MoneyR\x06amount\x12%\n" +
	"\x0epayment_status\x18\x05 \x01(\tR\rpaymentStatus\x123\n" +
	"\apaid_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"\xfe\x02\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12,\n" +
	"\x04type\x18\x06 \x01(\x0e2\x18.notify.NotificationTypeR\x04type\x128\n" +
	"\bpriority\x18\a \x01(\x0e2\x1c.notify.NotificationPriorityR\bpriority\x12I\n" +
	"\bmetadata\x18\b \x03(\v2-.notify.SendNotificationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd5\x02\n" +
	"\x1fSendTemplateNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12T\n" +
	"\tvariables\x18\x05 \x03(\v26.notify.SendTemplateNotificationRequest.VariablesEntryR\tvariables\x128\n" +
	"\bpriority\x18\x06 \x01(\x0e2\x1c.notify.NotificationPriorityR\bpriority\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xde\x02\n" +
	"\x1cSendBulkNotificationsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.notify.NotificationTypeR\x04type\x128\n" +
	"\bpriority\x18\x05 \x01(\x0e2\x1c.notify.NotificationPriorityR\bpriority\x12N\n" +
	"\bmetadata\x18\x06 \x03(\v22.notify.SendBulkNotificationsRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x16GetNotificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd5\x01\n" +
	"\x1dGetNotificationsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.notify.NotificationStatusR\x06status\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.notify.NotificationTypeR\x04type\"#\n" +
	"\x11MarkAsReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x14MarkAllAsReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"V\n" +
	"!ProcessInvoicePaymentEventRequest\x121\n" +
	"\x05event\x18\x01 \x01(\v2\x1b.notify.InvoicePaymentEventR\x05event\"\x88\x01\n" +
	"\x18SendNotificationResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.notify.NotificationR\fnotification\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x89\x01\n" +
	"\x1dSendBulkNotificationsResponse\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x05R\ttotalSent\x12!\n" +
	"\ftotal_failed\x18\x02 \x01(\x05R\vtotalFailed\x12&\n" +
	"\x0ffailed_user_ids\x18\x03 \x03(\tR\rfailedUserIds\"S\n" +
	"\x17GetNotificationResponse\x128\n" +
	"\fnotification\x18\x01 \x01(\v2\x14.notify.NotificationR\fnotification\"\x92\x01\n" +
	"\x18GetNotificationsResponse\x12:\n" +
	"\rnotifications\x18\x01 \x03(\v2\x14.notify.NotificationR\rnotifications\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"H\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x01\n" +
	"\"ProcessInvoicePaymentEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\rnotifications\x18\x03 \x03(\v2\x14.notify.NotificationR\rnotifications*\xa7\x01\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NOTIFICATION_TYPE_EMAIL\x10\x01\x12\x19\n" +
	"\x15NOTIFICATION_TYPE_SMS\x10\x02\x12\x1a\n" +
	"\x16NOTIFICATION_TYPE_PUSH\x10\x03\x12\x1c\n" +
	"\x18NOTIFICATION_TYPE_IN_APP\x10\x04*\xc0\x01\n" +
	"\x14NotificationPriority\x12%\n" +
	"!NOTIFICATION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19NOTIFICATION_PRIORITY_LOW\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_NORMAL\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_PRIORITY_HIGH\x10\x03\x12 \n" +
	"\x1cNOTIFICATION_PRIORITY_URGENT\x10\x04*\xbb\x01\n" +
	"\x12NotificationStatus\x12#\n" +
	"\x1fNOTIFICATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bNOTIFICATION_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18NOTIFICATION_STATUS_SENT\x10\x02\x12!\n" +
	"\x1dNOTIFICATION_STATUS_DELIVERED\x10\x03\x12\x1e\n" +
	"\x1aNOTIFICATION_STATUS_FAILED\x10\x042\x80\x05\n" +
	"\x13NotificationService\x12U\n" +
	"\x10SendNotification\x12\x1f.notify.SendNotificationRequest\x1a .notify.SendNotificationResponse\x12e\n" +
	"\x18SendTemplateNotification\x12'.notify.SendTemplateNotificationRequest\x1a .notify.SendNotificationResponse\x12d\n" +
	"\x15SendBulkNotifications\x12$.notify.SendBulkNotificationsRequest\x1a%.notify.SendBulkNotificationsResponse\x12R\n" +
	"\x0fGetNotification\x12\x1e.notify.GetNotificationRequest\x1a\x1f.notify.GetNotificationResponse\x12a\n" +
	"\x16GetNotificationsByUser\x12%.notify.GetNotificationsByUserRequest\x1a .notify.GetNotificationsResponse\x12C\n" +
	"\n" +
	"MarkAsRead\x12\x19.notify.MarkAsReadRequest\x1a\x1a.notify.MarkAsReadResponse\x12I\n" +
	"\rMarkAllAsRead\x12\x1c.notify.MarkAllAsReadRequest\x1a\x1a.notify.MarkAsReadResponse2\x8f\x01\n" +
	"\x18NotificationEventService\x12s\n" +
	"\x1aProcessInvoicePaymentEvent\x12).notify.ProcessInvoicePaymentEventRequest\x1a*.notify.ProcessInvoicePaymentEventResponseB<Z:github.com/educonnect/educonnect/internal/pkg/proto/notifyb\x06proto3"

var (
	file_notify_proto_rawDescOnce sync.Once
	file_notify_proto_rawDescData []byte
)

func file_notify_proto_rawDescGZIP() []byte {
	file_notify_proto_rawDescOnce.Do(func() {
		file_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_proto_rawDesc), len(file_notify_proto_rawDesc)))
	})
	return file_notify_proto_rawDescData
}

var file_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_notify_proto_goTypes = []any{
	(NotificationType)(0),                      // 0: notify.NotificationType
	(NotificationPriority)(0),                  // 1: notify.NotificationPriority
	(NotificationStatus)(0),                    // 2: notify.NotificationStatus
	(*NotificationTemplate)(nil),               // 3: notify.NotificationTemplate
	(*Notification)(nil),                       // 4: notify.Notification
	(*InvoicePaymentEvent)(nil),                // 5: notify.InvoicePaymentEvent
	(*SendNotificationRequest)(nil),            // 6: notify.SendNotificationRequest
	(*SendTemplateNotificationRequest)(nil),    // 7: notify.SendTemplateNotificationRequest
	(*SendBulkNotificationsRequest)(nil),       // 8: notify.SendBulkNotificationsRequest
	(*GetNotificationRequest)(nil),             // 9: notify.GetNotificationRequest
	(*GetNotificationsByUserRequest)(nil),      // 10: notify.GetNotificationsByUserRequest
	(*MarkAsReadRequest)(nil),                  // 11: notify.MarkAsReadRequest
	(*MarkAllAsReadRequest)(nil),               // 12: notify.MarkAllAsReadRequest
	(*ProcessInvoicePaymentEventRequest)(nil),  // 13: notify.ProcessInvoicePaymentEventRequest
	(*SendNotificationResponse)(nil),           // 14: notify.SendNotificationResponse
	(*SendBulkNotificationsResponse)(nil),      // 15: notify.SendBulkNotificationsResponse
	(*GetNotificationResponse)(nil),            // 16: notify.GetNotificationResponse
	(*GetNotificationsResponse)(nil),           // 17: notify.GetNotificationsResponse
	(*MarkAsReadResponse)(nil),                 // 18: notify.MarkAsReadResponse
	(*ProcessInvoicePaymentEventResponse)(nil), // 19: notify.ProcessInvoicePaymentEventResponse
	nil,                               // 20: notify.NotificationTemplate.VariablesEntry
	nil,                               // 21: notify.Notification.MetadataEntry
	nil,                               // 22: notify.SendNotificationRequest.MetadataEntry
	nil,                               // 23: notify.SendTemplateNotificationRequest.VariablesEntry
	nil,                               // 24: notify.SendBulkNotificationsRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
	(*common.Money)(nil),              // 26: common.Money
	(*common.PaginationRequest)(nil),  // 27: common.PaginationRequest
	(*common.PaginationResponse)(nil), // 28: common.PaginationResponse
}
var file_notify_proto_depIdxs = []int32{
	0,  // 0: notify.NotificationTemplate.type:type_name -> notify.NotificationType
	20, // 1: notify.NotificationTemplate.variables:type_name -> notify.NotificationTemplate.VariablesEntry
	25, // 2: notify.NotificationTemplate.created_at:type_name -> google.protobuf.Timestamp
	25, // 3: notify.NotificationTemplate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: notify.Notification.type:type_name -> notify.NotificationType
	1,  // 5: notify.Notification.priority:type_name -> notify.NotificationPriority
	2,  // 6: notify.Notification.status:type_name -> notify.NotificationStatus
	21, // 7: notify.Notification.metadata:type_name -> notify.Notification.MetadataEntry
	25, // 8: notify.Notification.scheduled_at:type_name -> google.protobuf.Timestamp
	25, // 9: notify.Notification.sent_at:type_name -> google.protobuf.Timestamp
	25, // 10: notify.Notification.delivered_at:type_name -> google.protobuf.Timestamp
	25, // 11: notify.Notification.created_at:type_name -> google.protobuf.Timestamp
	26, // 12: notify.InvoicePaymentEvent.amount:type_name -> common.Money
	25, // 13: notify.InvoicePaymentEvent.paid_at:type_name -> google.protobuf.Timestamp
	0,  // 14: notify.SendNotificationRequest.type:type_name -> notify.NotificationType
	1,  // 15: notify.SendNotificationRequest.priority:type_name -> notify.NotificationPriority
	22, // 16: notify.SendNotificationRequest.metadata:type_name -> notify.SendNotificationRequest.MetadataEntry
	23, // 17: notify.SendTemplateNotificationRequest.variables:type_name -> notify.SendTemplateNotificationRequest.VariablesEntry
	1,  // 18: notify.SendTemplateNotificationRequest.priority:type_name -> notify.NotificationPriority
	0,  // 19: notify.SendBulkNotificationsRequest.type:type_name -> notify.NotificationType
	1,  // 20: notify.SendBulkNotificationsRequest.priority:type_name -> notify.NotificationPriority
	24, // 21: notify.SendBulkNotificationsRequest.metadata:type_name -> notify.SendBulkNotificationsRequest.MetadataEntry
	27, // 22: notify.GetNotificationsByUserRequest.pagination:type_name -> common.PaginationRequest
	2,  // 23: notify.GetNotificationsByUserRequest.status:type_name -> notify.NotificationStatus
	0,  // 24: notify.GetNotificationsByUserRequest.type:type_name -> notify.NotificationType
	5,  // 25: notify.ProcessInvoicePaymentEventRequest.event:type_name -> notify.InvoicePaymentEvent
	4,  // 26: notify.SendNotificationResponse.notification:type_name -> notify.Notification
	4,  // 27: notify.GetNotificationResponse.notification:type_name -> notify.Notification
	4,  // 28: notify.GetNotificationsResponse.notifications:type_name -> notify.Notification
	28, // 29: notify.GetNotificationsResponse.pagination:type_name -> common.PaginationResponse
	4,  // 30: notify.ProcessInvoicePaymentEventResponse.notifications:type_name -> notify.Notification
	6,  // 31: notify.NotificationService.SendNotification:input_type -> notify.SendNotificationRequest
	7,  // 32: notify.NotificationService.SendTemplateNotification:input_type -> notify.SendTemplateNotificationRequest
	8,  // 33: notify.NotificationService.SendBulkNotifications:input_type -> notify.SendBulkNotificationsRequest
	9,  // 34: notify.NotificationService.GetNotification:input_type -> notify.GetNotificationRequest
	10, // 35: notify.NotificationService.GetNotificationsByUser:input_type -> notify.GetNotificationsByUserRequest
	11, // 36: notify.NotificationService.MarkAsRead:input_type -> notify.MarkAsReadRequest
	12, // 37: notify.NotificationService.MarkAllAsRead:input_type -> notify.MarkAllAsReadRequest
	13, // 38: notify.NotificationEventService.ProcessInvoicePaymentEvent:input_type -> notify.ProcessInvoicePaymentEventRequest
	14, // 39: notify.NotificationService.SendNotification:output_type -> notify.SendNotificationResponse
	14, // 40: notify.NotificationService.SendTemplateNotification:output_type -> notify.SendNotificationResponse
	15, // 41: notify.NotificationService.SendBulkNotifications:output_type -> notify.SendBulkNotificationsResponse
	16, // 42: notify.NotificationService.GetNotification:output_type -> notify.GetNotificationResponse
	17, // 43: notify.NotificationService.GetNotificationsByUser:output_type -> notify.GetNotificationsResponse
	18, // 44: notify.NotificationService.MarkAsRead:output_type -> notify.MarkAsReadResponse
	18, // 45: notify.NotificationService.MarkAllAsRead:output_type -> notify.MarkAsReadResponse
	19, // 46: notify.NotificationEventService.ProcessInvoicePaymentEvent:output_type -> notify.ProcessInvoicePaymentEventResponse
	39, // [39:47] is the sub-list for method output_type
	31, // [31:39] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_notify_proto_init() }
func file_notify_proto_init() {
	if File_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_proto_rawDesc), len(file_notify_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_notify_proto_goTypes,
		DependencyIndexes: file_notify_proto_depIdxs,
		EnumInfos:         file_notify_proto_enumTypes,
		MessageInfos:      file_notify_proto_msgTypes,
	}.Build()
	File_notify_proto = out.File
	file_notify_proto_goTypes = nil
	file_notify_proto_depIdxs = nil
}
