// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: school.proto

package school

import (
	common "github.com/educonnect/educonnect/internal/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentStatus int32

const (
	StudentStatus_STUDENT_STATUS_UNSPECIFIED StudentStatus = 0
	StudentStatus_STUDENT_STATUS_ACTIVE      StudentStatus = 1
	StudentStatus_STUDENT_STATUS_INACTIVE    StudentStatus = 2
	StudentStatus_STUDENT_STATUS_GRADUATED   StudentStatus = 3
	StudentStatus_STUDENT_STATUS_SUSPENDED   StudentStatus = 4
)

// Enum value maps for StudentStatus.
var (
	StudentStatus_name = map[int32]string{
		0: "STUDENT_STATUS_UNSPECIFIED",
		1: "STUDENT_STATUS_ACTIVE",
		2: "STUDENT_STATUS_INACTIVE",
		3: "STUDENT_STATUS_GRADUATED",
		4: "STUDENT_STATUS_SUSPENDED",
	}
	StudentStatus_value = map[string]int32{
		"STUDENT_STATUS_UNSPECIFIED": 0,
		"STUDENT_STATUS_ACTIVE":      1,
		"STUDENT_STATUS_INACTIVE":    2,
		"STUDENT_STATUS_GRADUATED":   3,
		"STUDENT_STATUS_SUSPENDED":   4,
	}
)

func (x StudentStatus) Enum() *StudentStatus {
	p := new(StudentStatus)
	*p = x
	return p
}

func (x StudentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_school_proto_enumTypes[0].Descriptor()
}

func (StudentStatus) Type() protoreflect.EnumType {
	return &file_school_proto_enumTypes[0]
}

func (x StudentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudentStatus.Descriptor instead.
func (StudentStatus) EnumDescriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{0}
}

type GradeType int32

const (
	GradeType_GRADE_TYPE_UNSPECIFIED GradeType = 0
	GradeType_GRADE_TYPE_MIDTERM     GradeType = 1
	GradeType_GRADE_TYPE_FINAL       GradeType = 2
	GradeType_GRADE_TYPE_ASSIGNMENT  GradeType = 3
	GradeType_GRADE_TYPE_QUIZ        GradeType = 4
)

// Enum value maps for GradeType.
var (
	GradeType_name = map[int32]string{
		0: "GRADE_TYPE_UNSPECIFIED",
		1: "GRADE_TYPE_MIDTERM",
		2: "GRADE_TYPE_FINAL",
		3: "GRADE_TYPE_ASSIGNMENT",
		4: "GRADE_TYPE_QUIZ",
	}
	GradeType_value = map[string]int32{
		"GRADE_TYPE_UNSPECIFIED": 0,
		"GRADE_TYPE_MIDTERM":     1,
		"GRADE_TYPE_FINAL":       2,
		"GRADE_TYPE_ASSIGNMENT":  3,
		"GRADE_TYPE_QUIZ":        4,
	}
)

func (x GradeType) Enum() *GradeType {
	p := new(GradeType)
	*p = x
	return p
}

func (x GradeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GradeType) Descriptor() protoreflect.EnumDescriptor {
	return file_school_proto_enumTypes[1].Descriptor()
}

func (GradeType) Type() protoreflect.EnumType {
	return &file_school_proto_enumTypes[1]
}

func (x GradeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GradeType.Descriptor instead.
func (GradeType) EnumDescriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{1}
}

type AttendanceStatus int32

const (
	AttendanceStatus_ATTENDANCE_STATUS_UNSPECIFIED AttendanceStatus = 0
	AttendanceStatus_ATTENDANCE_STATUS_PRESENT     AttendanceStatus = 1
	AttendanceStatus_ATTENDANCE_STATUS_ABSENT      AttendanceStatus = 2
	AttendanceStatus_ATTENDANCE_STATUS_LATE        AttendanceStatus = 3
	AttendanceStatus_ATTENDANCE_STATUS_EXCUSED     AttendanceStatus = 4
)

// Enum value maps for AttendanceStatus.
var (
	AttendanceStatus_name = map[int32]string{
		0: "ATTENDANCE_STATUS_UNSPECIFIED",
		1: "ATTENDANCE_STATUS_PRESENT",
		2: "ATTENDANCE_STATUS_ABSENT",
		3: "ATTENDANCE_STATUS_LATE",
		4: "ATTENDANCE_STATUS_EXCUSED",
	}
	AttendanceStatus_value = map[string]int32{
		"ATTENDANCE_STATUS_UNSPECIFIED": 0,
		"ATTENDANCE_STATUS_PRESENT":     1,
		"ATTENDANCE_STATUS_ABSENT":      2,
		"ATTENDANCE_STATUS_LATE":        3,
		"ATTENDANCE_STATUS_EXCUSED":     4,
	}
)

func (x AttendanceStatus) Enum() *AttendanceStatus {
	p := new(AttendanceStatus)
	*p = x
	return p
}

func (x AttendanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttendanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_school_proto_enumTypes[2].Descriptor()
}

func (AttendanceStatus) Type() protoreflect.EnumType {
	return &file_school_proto_enumTypes[2]
}

func (x AttendanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttendanceStatus.Descriptor instead.
func (AttendanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{2}
}

type Student struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	StudentCode   string                 `protobuf:"bytes,4,opt,name=student_code,json=studentCode,proto3" json:"student_code,omitempty"`
	Status        StudentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=school.StudentStatus" json:"status,omitempty"`
	User          *common.UserRef        `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Student) Reset() {
	*x = Student{}
	mi := &file_school_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Student) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Student) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *Student) GetStudentCode() string {
	if x != nil {
		return x.StudentCode
	}
	return ""
}

func (x *Student) GetStatus() StudentStatus {
	if x != nil {
		return x.Status
	}
	return StudentStatus_STUDENT_STATUS_UNSPECIFIED
}

func (x *Student) GetUser() *common.UserRef {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Student) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Student) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SchoolClass struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AcademicYearId    string                 `protobuf:"bytes,3,opt,name=academic_year_id,json=academicYearId,proto3" json:"academic_year_id,omitempty"`
	HomeroomTeacherId string                 `protobuf:"bytes,4,opt,name=homeroom_teacher_id,json=homeroomTeacherId,proto3" json:"homeroom_teacher_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchoolClass) Reset() {
	*x = SchoolClass{}
	mi := &file_school_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolClass) ProtoMessage() {}

func (x *SchoolClass) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolClass.ProtoReflect.Descriptor instead.
func (*SchoolClass) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{1}
}

func (x *SchoolClass) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SchoolClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchoolClass) GetAcademicYearId() string {
	if x != nil {
		return x.AcademicYearId
	}
	return ""
}

func (x *SchoolClass) GetHomeroomTeacherId() string {
	if x != nil {
		return x.HomeroomTeacherId
	}
	return ""
}

func (x *SchoolClass) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SchoolClass) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SubjectCode   string                 `protobuf:"bytes,3,opt,name=subject_code,json=subjectCode,proto3" json:"subject_code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_school_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{2}
}

func (x *Subject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subject) GetSubjectCode() string {
	if x != nil {
		return x.SubjectCode
	}
	return ""
}

func (x *Subject) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Grade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	TeacherId     string                 `protobuf:"bytes,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Type          GradeType              `protobuf:"varint,6,opt,name=type,proto3,enum=school.GradeType" json:"type,omitempty"`
	Semester      int32                  `protobuf:"varint,7,opt,name=semester,proto3" json:"semester,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_school_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{3}
}

func (x *Grade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grade) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Grade) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Grade) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *Grade) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Grade) GetType() GradeType {
	if x != nil {
		return x.Type
	}
	return GradeType_GRADE_TYPE_UNSPECIFIED
}

func (x *Grade) GetSemester() int32 {
	if x != nil {
		return x.Semester
	}
	return 0
}

func (x *Grade) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Grade) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	TeacherId     string                 `protobuf:"bytes,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,5,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	Period        int32                  `protobuf:"varint,6,opt,name=period,proto3" json:"period,omitempty"`
	Room          string                 `protobuf:"bytes,7,opt,name=room,proto3" json:"room,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_school_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{4}
}

func (x *Schedule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Schedule) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *Schedule) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *Schedule) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *Schedule) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *Schedule) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Schedule) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Schedule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Attendance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,3,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Status        AttendanceStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=school.AttendanceStatus" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendance) Reset() {
	*x = Attendance{}
	mi := &file_school_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendance) ProtoMessage() {}

func (x *Attendance) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendance.ProtoReflect.Descriptor instead.
func (*Attendance) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{5}
}

func (x *Attendance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Attendance) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Attendance) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Attendance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Attendance) GetStatus() AttendanceStatus {
	if x != nil {
		return x.Status
	}
	return AttendanceStatus_ATTENDANCE_STATUS_UNSPECIFIED
}

func (x *Attendance) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Attendance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentRequest) Reset() {
	*x = GetStudentRequest{}
	mi := &file_school_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentRequest) ProtoMessage() {}

func (x *GetStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentRequest.ProtoReflect.Descriptor instead.
func (*GetStudentRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{6}
}

func (x *GetStudentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStudentByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentByUserIdRequest) Reset() {
	*x = GetStudentByUserIdRequest{}
	mi := &file_school_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentByUserIdRequest) ProtoMessage() {}

func (x *GetStudentByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetStudentByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{7}
}

func (x *GetStudentByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListStudentsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ClassId       string                    `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Status        StudentStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=school.StudentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsRequest) Reset() {
	*x = ListStudentsRequest{}
	mi := &file_school_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsRequest) ProtoMessage() {}

func (x *ListStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListStudentsRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{8}
}

func (x *ListStudentsRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ListStudentsRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListStudentsRequest) GetStatus() StudentStatus {
	if x != nil {
		return x.Status
	}
	return StudentStatus_STUDENT_STATUS_UNSPECIFIED
}

type CreateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	StudentCode   string                 `protobuf:"bytes,3,opt,name=student_code,json=studentCode,proto3" json:"student_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentRequest) Reset() {
	*x = CreateStudentRequest{}
	mi := &file_school_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRequest) ProtoMessage() {}

func (x *CreateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateStudentRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{9}
}

func (x *CreateStudentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateStudentRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *CreateStudentRequest) GetStudentCode() string {
	if x != nil {
		return x.StudentCode
	}
	return ""
}

type UpdateStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClassId       string                 `protobuf:"bytes,2,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Status        StudentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=school.StudentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentRequest) Reset() {
	*x = UpdateStudentRequest{}
	mi := &file_school_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentRequest) ProtoMessage() {}

func (x *UpdateStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudentRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStudentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStudentRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *UpdateStudentRequest) GetStatus() StudentStatus {
	if x != nil {
		return x.Status
	}
	return StudentStatus_STUDENT_STATUS_UNSPECIFIED
}

type GetClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassRequest) Reset() {
	*x = GetClassRequest{}
	mi := &file_school_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassRequest) ProtoMessage() {}

func (x *GetClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassRequest.ProtoReflect.Descriptor instead.
func (*GetClassRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{11}
}

func (x *GetClassRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListClassesRequest struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	AcademicYearId string                    `protobuf:"bytes,1,opt,name=academic_year_id,json=academicYearId,proto3" json:"academic_year_id,omitempty"`
	Pagination     *common.PaginationRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListClassesRequest) Reset() {
	*x = ListClassesRequest{}
	mi := &file_school_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassesRequest) ProtoMessage() {}

func (x *ListClassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassesRequest.ProtoReflect.Descriptor instead.
func (*ListClassesRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{12}
}

func (x *ListClassesRequest) GetAcademicYearId() string {
	if x != nil {
		return x.AcademicYearId
	}
	return ""
}

func (x *ListClassesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetGradesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StudentId     string                    `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	SubjectId     string                    `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Semester      int32                     `protobuf:"varint,3,opt,name=semester,proto3" json:"semester,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradesRequest) Reset() {
	*x = GetGradesRequest{}
	mi := &file_school_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradesRequest) ProtoMessage() {}

func (x *GetGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradesRequest.ProtoReflect.Descriptor instead.
func (*GetGradesRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{13}
}

func (x *GetGradesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetGradesRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetGradesRequest) GetSemester() int32 {
	if x != nil {
		return x.Semester
	}
	return 0
}

func (x *GetGradesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateGradeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	TeacherId     string                 `protobuf:"bytes,3,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Type          GradeType              `protobuf:"varint,5,opt,name=type,proto3,enum=school.GradeType" json:"type,omitempty"`
	Semester      int32                  `protobuf:"varint,6,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGradeRequest) Reset() {
	*x = CreateGradeRequest{}
	mi := &file_school_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGradeRequest) ProtoMessage() {}

func (x *CreateGradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGradeRequest.ProtoReflect.Descriptor instead.
func (*CreateGradeRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGradeRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateGradeRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CreateGradeRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *CreateGradeRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateGradeRequest) GetType() GradeType {
	if x != nil {
		return x.Type
	}
	return GradeType_GRADE_TYPE_UNSPECIFIED
}

func (x *CreateGradeRequest) GetSemester() int32 {
	if x != nil {
		return x.Semester
	}
	return 0
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_school_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{15}
}

func (x *GetScheduleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ClassId       string                    `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	TeacherId     string                    `protobuf:"bytes,2,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Pagination    *common.PaginationRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_school_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{16}
}

func (x *ListSchedulesRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *ListSchedulesRequest) GetTeacherId() string {
	if x != nil {
		return x.TeacherId
	}
	return ""
}

func (x *ListSchedulesRequest) GetPagination() *common.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentResponse) Reset() {
	*x = GetStudentResponse{}
	mi := &file_school_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentResponse) ProtoMessage() {}

func (x *GetStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentResponse.ProtoReflect.Descriptor instead.
func (*GetStudentResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{17}
}

func (x *GetStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

type ListStudentsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Students      []*Student                 `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudentsResponse) Reset() {
	*x = ListStudentsResponse{}
	mi := &file_school_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudentsResponse) ProtoMessage() {}

func (x *ListStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudentsResponse.ProtoReflect.Descriptor instead.
func (*ListStudentsResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{18}
}

func (x *ListStudentsResponse) GetStudents() []*Student {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *ListStudentsResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentResponse) Reset() {
	*x = CreateStudentResponse{}
	mi := &file_school_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentResponse) ProtoMessage() {}

func (x *CreateStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentResponse.ProtoReflect.Descriptor instead.
func (*CreateStudentResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{19}
}

func (x *CreateStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *CreateStudentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateStudentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Student       *Student               `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudentResponse) Reset() {
	*x = UpdateStudentResponse{}
	mi := &file_school_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudentResponse) ProtoMessage() {}

func (x *UpdateStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudentResponse.ProtoReflect.Descriptor instead.
func (*UpdateStudentResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateStudentResponse) GetStudent() *Student {
	if x != nil {
		return x.Student
	}
	return nil
}

func (x *UpdateStudentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStudentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *SchoolClass           `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassResponse) Reset() {
	*x = GetClassResponse{}
	mi := &file_school_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassResponse) ProtoMessage() {}

func (x *GetClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassResponse.ProtoReflect.Descriptor instead.
func (*GetClassResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{21}
}

func (x *GetClassResponse) GetClass() *SchoolClass {
	if x != nil {
		return x.Class
	}
	return nil
}

type ListClassesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Classes       []*SchoolClass             `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassesResponse) Reset() {
	*x = ListClassesResponse{}
	mi := &file_school_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassesResponse) ProtoMessage() {}

func (x *ListClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassesResponse.ProtoReflect.Descriptor instead.
func (*ListClassesResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{22}
}

func (x *ListClassesResponse) GetClasses() []*SchoolClass {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *ListClassesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetGradesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Grades        []*Grade                   `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGradesResponse) Reset() {
	*x = GetGradesResponse{}
	mi := &file_school_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGradesResponse) ProtoMessage() {}

func (x *GetGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGradesResponse.ProtoReflect.Descriptor instead.
func (*GetGradesResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{23}
}

func (x *GetGradesResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *GetGradesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type CreateGradeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         *Grade                 `protobuf:"bytes,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGradeResponse) Reset() {
	*x = CreateGradeResponse{}
	mi := &file_school_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGradeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGradeResponse) ProtoMessage() {}

func (x *CreateGradeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGradeResponse.ProtoReflect.Descriptor instead.
func (*CreateGradeResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{24}
}

func (x *CreateGradeResponse) GetGrade() *Grade {
	if x != nil {
		return x.Grade
	}
	return nil
}

func (x *CreateGradeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateGradeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *Schedule              `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleResponse) Reset() {
	*x = GetScheduleResponse{}
	mi := &file_school_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleResponse) ProtoMessage() {}

func (x *GetScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{25}
}

func (x *GetScheduleResponse) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Schedules     []*Schedule                `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	Pagination    *common.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_school_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_school_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_school_proto_rawDescGZIP(), []int{26}
}

func (x *ListSchedulesResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *ListSchedulesResponse) GetPagination() *common.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_school_proto protoreflect.FileDescriptor

const file_school_proto_rawDesc = "" +
	"\n" +
	"\fschool.proto\x12\x06school\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n" +
	"\aStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\x12!\n" +
	"\fstudent_code\x18\x04 \x01(\tR\vstudentCode\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.school.StudentStatusR\x06status\x12#\n" +
	"\x04user\x18\x06 \x01(\v2\x0f.common.UserRefR\x04user\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x02\n" +
	"\vSchoolClass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x10academic_year_id\x18\x03 \x01(\tR\x0eacademicYearId\x12.\n" +
	"\x13homeroom_teacher_id\x18\x04 \x01(\tR\x11homeroomTeacherId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x01\n" +
	"\aSubject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fsubject_code\x18\x03 \x01(\tR\vsubjectCode\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc3\x02\n" +
	"\x05Grade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x04 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12%\n" +
	"\x04type\x18\x06 \x01(\x0e2\x11.school.GradeTypeR\x04type\x12\x1a\n" +
	"\bsemester\x18\a \x01(\x05R\bsemester\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfa\x01\n" +
	"\bSchedule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x04 \x01(\tR\tteacherId\x12\x1e\n" +
	"\vday_of_week\x18\x05 \x01(\x05R\tdayOfWeek\x12\x16\n" +
	"\x06period\x18\x06 \x01(\x05R\x06period\x12\x12\n" +
	"\x04room\x18\a \x01(\tR\x04room\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf1\x01\n" +
	"\n" +
	"Attendance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1f\n" +
	"\vschedule_id\x18\x03 \x01(\tR\n" +
	"scheduleId\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.school.AttendanceStatusR\x06status\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"#\n" +
	"\x11GetStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x19GetStudentByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9a\x01\n" +
	"\x13ListStudentsRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.school.StudentStatusR\x06status\"m\n" +
	"\x14CreateStudentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12!\n" +
	"\fstudent_code\x18\x03 \x01(\tR\vstudentCode\"p\n" +
	"\x14UpdateStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bclass_id\x18\x02 \x01(\tR\aclassId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.school.StudentStatusR\x06status\"!\n" +
	"\x0fGetClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x12ListClassesRequest\x12(\n" +
	"\x10academic_year_id\x18\x01 \x01(\tR\x0eacademicYearId\x129\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\xa7\x01\n" +
	"\x10GetGradesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1a\n" +
	"\bsemester\x18\x03 \x01(\x05R\bsemester\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"\xca\x01\n" +
	"\x12CreateGradeRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x03 \x01(\tR\tteacherId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12%\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.school.GradeTypeR\x04type\x12\x1a\n" +
	"\bsemester\x18\x06 \x01(\x05R\bsemester\"$\n" +
	"\x12GetScheduleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8b\x01\n" +
	"\x14ListSchedulesRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x02 \x01(\tR\tteacherId\x129\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x19.common.PaginationRequestR\n" +
	"pagination\"?\n" +
	"\x12GetStudentResponse\x12)\n" +
	"\astudent\x18\x01 \x01(\v2\x0f.school.StudentR\astudent\"\x7f\n" +
	"\x14ListStudentsResponse\x12+\n" +
	"\bstudents\x18\x01 \x03(\v2\x0f.school.StudentR\bstudents\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"v\n" +
	"\x15CreateStudentResponse\x12)\n" +
	"\astudent\x18\x01 \x01(\v2\x0f.school.StudentR\astudent\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"v\n" +
	"\x15UpdateStudentResponse\x12)\n" +
	"\astudent\x18\x01 \x01(\v2\x0f.school.StudentR\astudent\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\x10GetClassResponse\x12)\n" +
	"\x05class\x18\x01 \x01(\v2\x13.school.SchoolClassR\x05class\"\x80\x01\n" +
	"\x13ListClassesResponse\x12-\n" +
	"\aclasses\x18\x01 \x03(\v2\x13.school.SchoolClassR\aclasses\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"v\n" +
	"\x11GetGradesResponse\x12%\n" +
	"\x06grades\x18\x01 \x03(\v2\r.school.GradeR\x06grades\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination\"n\n" +
	"\x13CreateGradeResponse\x12#\n" +
	"\x05grade\x18\x01 \x01(\v2\r.school.GradeR\x05grade\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"C\n" +
	"\x13GetScheduleResponse\x12,\n" +
	"\bschedule\x18\x01 \x01(\v2\x10.school.ScheduleR\bschedule\"\x83\x01\n" +
	"\x15ListSchedulesResponse\x12.\n" +
	"\tschedules\x18\x01 \x03(\v2\x10.school.ScheduleR\tschedules\x12:\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1a.common.PaginationResponseR\n" +
	"pagination*\xa3\x01\n" +
	"\rStudentStatus\x12\x1e\n" +
	"\x1aSTUDENT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15STUDENT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17STUDENT_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18STUDENT_STATUS_GRADUATED\x10\x03\x12\x1c\n" +
	"\x18STUDENT_STATUS_SUSPENDED\x10\x04*\x85\x01\n" +
	"\tGradeType\x12\x1a\n" +
	"\x16GRADE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12GRADE_TYPE_MIDTERM\x10\x01\x12\x14\n" +
	"\x10GRADE_TYPE_FINAL\x10\x02\x12\x19\n" +
	"\x15GRADE_TYPE_ASSIGNMENT\x10\x03\x12\x13\n" +
	"\x0fGRADE_TYPE_QUIZ\x10\x04*\xad\x01\n" +
	"\x10AttendanceStatus\x12!\n" +
	"\x1dATTENDANCE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ATTENDANCE_STATUS_PRESENT\x10\x01\x12\x1c\n" +
	"\x18ATTENDANCE_STATUS_ABSENT\x10\x02\x12\x1a\n" +
	"\x16ATTENDANCE_STATUS_LATE\x10\x03\x12\x1d\n" +
	"\x19ATTENDANCE_STATUS_EXCUSED\x10\x042\x91\x03\n" +
	"\x0eStudentService\x12C\n" +
	"\n" +
	"GetStudent\x12\x19.school.GetStudentRequest\x1a\x1a.school.GetStudentResponse\x12S\n" +
	"\x12GetStudentByUserId\x12!.school.GetStudentByUserIdRequest\x1a\x1a.school.GetStudentResponse\x12I\n" +
	"\fListStudents\x12\x1b.school.ListStudentsRequest\x1a\x1c.school.ListStudentsResponse\x12L\n" +
	"\rCreateStudent\x12\x1c.school.CreateStudentRequest\x1a\x1d.school.CreateStudentResponse\x12L\n" +
	"\rUpdateStudent\x12\x1c.school.UpdateStudentRequest\x1a\x1d.school.UpdateStudentResponse2\x95\x01\n" +
	"\fClassService\x12=\n" +
	"\bGetClass\x12\x17.school.GetClassRequest\x1a\x18.school.GetClassResponse\x12F\n" +
	"\vListClasses\x12\x1a.school.ListClassesRequest\x1a\x1b.school.ListClassesResponse2\x98\x01\n" +
	"\fGradeService\x12@\n" +
	"\tGetGrades\x12\x18.school.GetGradesRequest\x1a\x19.school.GetGradesResponse\x12F\n" +
	"\vCreateGrade\x12\x1a.school.CreateGradeRequest\x1a\x1b.school.CreateGradeResponse2\xa7\x01\n" +
	"\x0fScheduleService\x12F\n" +
	"\vGetSchedule\x12\x1a.school.GetScheduleRequest\x1a\x1b.school.GetScheduleResponse\x12L\n" +
	"\rListSchedules\x12\x1c.school.ListSchedulesRequest\x1a\x1d.school.ListSchedulesResponseB<Z:github.com/educonnect/educonnect/internal/pkg/proto/schoolb\x06proto3"

var (
	file_school_proto_rawDescOnce sync.Once
	file_school_proto_rawDescData []byte
)

func file_school_proto_rawDescGZIP() []byte {
	file_school_proto_rawDescOnce.Do(func() {
		file_school_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_school_proto_rawDesc), len(file_school_proto_rawDesc)))
	})
	return file_school_proto_rawDescData
}

var file_school_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_school_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_school_proto_goTypes = []any{
	(StudentStatus)(0),                // 0: school.StudentStatus
	(GradeType)(0),                    // 1: school.GradeType
	(AttendanceStatus)(0),             // 2: school.AttendanceStatus
	(*Student)(nil),                   // 3: school.Student
	(*SchoolClass)(nil),               // 4: school.SchoolClass
	(*Subject)(nil),                   // 5: school.Subject
	(*Grade)(nil),                     // 6: school.Grade
	(*Schedule)(nil),                  // 7: school.Schedule
	(*Attendance)(nil),                // 8: school.Attendance
	(*GetStudentRequest)(nil),         // 9: school.GetStudentRequest
	(*GetStudentByUserIdRequest)(nil), // 10: school.GetStudentByUserIdRequest
	(*ListStudentsRequest)(nil),       // 11: school.ListStudentsRequest
	(*CreateStudentRequest)(nil),      // 12: school.CreateStudentRequest
	(*UpdateStudentRequest)(nil),      // 13: school.UpdateStudentRequest
	(*GetClassRequest)(nil),           // 14: school.GetClassRequest
	(*ListClassesRequest)(nil),        // 15: school.ListClassesRequest
	(*GetGradesRequest)(nil),          // 16: school.GetGradesRequest
	(*CreateGradeRequest)(nil),        // 17: school.CreateGradeRequest
	(*GetScheduleRequest)(nil),        // 18: school.GetScheduleRequest
	(*ListSchedulesRequest)(nil),      // 19: school.ListSchedulesRequest
	(*GetStudentResponse)(nil),        // 20: school.GetStudentResponse
	(*ListStudentsResponse)(nil),      // 21: school.ListStudentsResponse
	(*CreateStudentResponse)(nil),     // 22: school.CreateStudentResponse
	(*UpdateStudentResponse)(nil),     // 23: school.UpdateStudentResponse
	(*GetClassResponse)(nil),          // 24: school.GetClassResponse
	(*ListClassesResponse)(nil),       // 25: school.ListClassesResponse
	(*GetGradesResponse)(nil),         // 26: school.GetGradesResponse
	(*CreateGradeResponse)(nil),       // 27: school.CreateGradeResponse
	(*GetScheduleResponse)(nil),       // 28: school.GetScheduleResponse
	(*ListSchedulesResponse)(nil),     // 29: school.ListSchedulesResponse
	(*common.UserRef)(nil),            // 30: common.UserRef
	(*timestamppb.Timestamp)(nil),     // 31: google.protobuf.Timestamp
	(*common.PaginationRequest)(nil),  // 32: common.PaginationRequest
	(*common.PaginationResponse)(nil), // 33: common.PaginationResponse
}
var file_school_proto_depIdxs = []int32{
	0,  // 0: school.Student.status:type_name -> school.StudentStatus
	30, // 1: school.Student.user:type_name -> common.UserRef
	31, // 2: school.Student.created_at:type_name -> google.protobuf.Timestamp
	31, // 3: school.Student.updated_at:type_name -> google.protobuf.Timestamp
	31, // 4: school.SchoolClass.created_at:type_name -> google.protobuf.Timestamp
	31, // 5: school.SchoolClass.updated_at:type_name -> google.protobuf.Timestamp
	31, // 6: school.Subject.created_at:type_name -> google.protobuf.Timestamp
	1,  // 7: school.Grade.type:type_name -> school.GradeType
	31, // 8: school.Grade.created_at:type_name -> google.protobuf.Timestamp
	31, // 9: school.Grade.updated_at:type_name -> google.protobuf.Timestamp
	31, // 10: school.Schedule.created_at:type_name -> google.protobuf.Timestamp
	2,  // 11: school.Attendance.status:type_name -> school.AttendanceStatus
	31, // 12: school.Attendance.created_at:type_name -> google.protobuf.Timestamp
	32, // 13: school.ListStudentsRequest.pagination:type_name -> common.PaginationRequest
	0,  // 14: school.ListStudentsRequest.status:type_name -> school.StudentStatus
	0,  // 15: school.UpdateStudentRequest.status:type_name -> school.StudentStatus
	32, // 16: school.ListClassesRequest.pagination:type_name -> common.PaginationRequest
	32, // 17: school.GetGradesRequest.pagination:type_name -> common.PaginationRequest
	1,  // 18: school.CreateGradeRequest.type:type_name -> school.GradeType
	32, // 19: school.ListSchedulesRequest.pagination:type_name -> common.PaginationRequest
	3,  // 20: school.GetStudentResponse.student:type_name -> school.Student
	3,  // 21: school.ListStudentsResponse.students:type_name -> school.Student
	33, // 22: school.ListStudentsResponse.pagination:type_name -> common.PaginationResponse
	3,  // 23: school.CreateStudentResponse.student:type_name -> school.Student
	3,  // 24: school.UpdateStudentResponse.student:type_name -> school.Student
	4,  // 25: school.GetClassResponse.class:type_name -> school.SchoolClass
	4,  // 26: school.ListClassesResponse.classes:type_name -> school.SchoolClass
	33, // 27: school.ListClassesResponse.pagination:type_name -> common.PaginationResponse
	6,  // 28: school.GetGradesResponse.grades:type_name -> school.Grade
	33, // 29: school.GetGradesResponse.pagination:type_name -> common.PaginationResponse
	6,  // 30: school.CreateGradeResponse.grade:type_name -> school.Grade
	7,  // 31: school.GetScheduleResponse.schedule:type_name -> school.Schedule
	7,  // 32: school.ListSchedulesResponse.schedules:type_name -> school.Schedule
	33, // 33: school.ListSchedulesResponse.pagination:type_name -> common.PaginationResponse
	9,  // 34: school.StudentService.GetStudent:input_type -> school.GetStudentRequest
	10, // 35: school.StudentService.GetStudentByUserId:input_type -> school.GetStudentByUserIdRequest
	11, // 36: school.StudentService.ListStudents:input_type -> school.ListStudentsRequest
	12, // 37: school.StudentService.CreateStudent:input_type -> school.CreateStudentRequest
	13, // 38: school.StudentService.UpdateStudent:input_type -> school.UpdateStudentRequest
	14, // 39: school.ClassService.GetClass:input_type -> school.GetClassRequest
	15, // 40: school.ClassService.ListClasses:input_type -> school.ListClassesRequest
	16, // 41: school.GradeService.GetGrades:input_type -> school.GetGradesRequest
	17, // 42: school.GradeService.CreateGrade:input_type -> school.CreateGradeRequest
	18, // 43: school.ScheduleService.GetSchedule:input_type -> school.GetScheduleRequest
	19, // 44: school.ScheduleService.ListSchedules:input_type -> school.ListSchedulesRequest
	20, // 45: school.StudentService.GetStudent:output_type -> school.GetStudentResponse
	20, // 46: school.StudentService.GetStudentByUserId:output_type -> school.GetStudentResponse
	21, // 47: school.StudentService.ListStudents:output_type -> school.ListStudentsResponse
	22, // 48: school.StudentService.CreateStudent:output_type -> school.CreateStudentResponse
	23, // 49: school.StudentService.UpdateStudent:output_type -> school.UpdateStudentResponse
	24, // 50: school.ClassService.GetClass:output_type -> school.GetClassResponse
	25, // 51: school.ClassService.ListClasses:output_type -> school.ListClassesResponse
	26, // 52: school.GradeService.GetGrades:output_type -> school.GetGradesResponse
	27, // 53: school.GradeService.CreateGrade:output_type -> school.CreateGradeResponse
	28, // 54: school.ScheduleService.GetSchedule:output_type -> school.GetScheduleResponse
	29, // 55: school.ScheduleService.ListSchedules:output_type -> school.ListSchedulesResponse
	45, // [45:56] is the sub-list for method output_type
	34, // [34:45] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_school_proto_init() }
func file_school_proto_init() {
	if File_school_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_school_proto_rawDesc), len(file_school_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_school_proto_goTypes,
		DependencyIndexes: file_school_proto_depIdxs,
		EnumInfos:         file_school_proto_enumTypes,
		MessageInfos:      file_school_proto_msgTypes,
	}.Build()
	File_school_proto = out.File
	file_school_proto_goTypes = nil
	file_school_proto_depIdxs = nil
}
